version: 2.1
orbs:
  coveralls:  coveralls/coveralls@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Execute Pipeline (Build Source -> Test -> Build Web Server)
          command: |
            docker build -f integration.Dockerfile . -t lemon-mart:$CIRCLE_BRANCH
            mkdir -p docker-cache
            docker save lemon-mart:$CIRCLE_BRANCH | gzip > docker-cache/built-image.tar.gz
      - save_cache:
          key: build-image-{{ .BuildNum }}
          paths:
            - docker-cache
      - run: npm test -- --watch=false --code-coverage
      - run: npm run e2e
      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      - coveralls/upload

      - run :
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/lemon-mart

      - store_artifacts:
          path: dist.tar.gz

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
