version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      # force update the webdriver
      # - run: cd ./node_modules/protractor && npm i webdrivermanager@latest

      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm folder"
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: npm run style
      - run: npm run lint
      - run: npm run build:prod
      - run: npm run test:coverage -- --watch=false --code-coverage
      - run: npm run e2e

      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      # upload coverage report to coveralls for readme badge support
      # require config.yml version 2.1 and orbs: coveralls: coveralls/coveralls@1.0.4
      # requires coveralls account and token nameed COVERALLS_REPO_TOKEN specific to repo to be stored in CircleCI
      # - coveralls/upload

      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/lemon-mart
      - store_artifacts:
          path: dist.tar.gz

      - run:
          name: Move compiled app to workspace
          command:
            set -exu
            mkdir -p /tmp/workspace/dist
            mv dist/lemon-mart /tmp/workspace/dist/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/lemon-mart
  deploy:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npx now --token $NOW_TOKEN --platform-version 2 --prod /tmp/workspace/dist/lemon-mart --confirm

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
  # build-and-test-and-apporval-deploy:
  #   jobs:
  #     - build
  #     - hold:
  #       type: apporval
  #       requires:
  #         - build
  #       filters:
  #         branches:
  #           only: master
  #     - deploy:
  #         requires:
  #           - hold
